# ansible/inventory/hosts.yml
---
# Inventory defines which servers Ansible manages
# Think of this as your "server address book"

all:
  children:
    ec2_servers:              # Group name for our EC2 instances
      hosts:
        web_server:           # Friendly name for our server
          ansible_host: "{{ lookup('env', 'EC2_HOST') or groups['localhost'][0] }}"
          ansible_user: "{{ lookup('env', 'EC2_USER') or 'ubuntu' }}"
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          
          # Server-specific variables
          server_role: webserver
          environment: production
          
      # Group variables for all EC2 servers
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_timeout: 30
        ansible_become: yes
        ansible_become_method: sudo

# Alternative static configuration (uncomment and modify if needed):
# all:
#   children:
#     ec2_servers:
#       hosts:
#         web_server:
#           ansible_host: YOUR_EC2_PUBLIC_IP_HERE
#           ansible_user: ubuntu
#           ansible_ssh_private_key_file: ~/.ssh/id_rsa