# ansible/playbooks/deploy-nginx.yml
---
- name: Deploy NGINX to EC2 Instance
  hosts: ec2_servers
  become: yes
  gather_facts: yes

  vars:
    nginx_port: 80

  tasks:
    # Task 1: Update apt package cache
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [system]

    # Task 2: Install NGINX
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      notify: restart nginx
      tags: [nginx]

    # Task 3: Start and enable NGINX service
    - name: Start and enable NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes
      tags: [nginx]

    # Task 4: Deploy custom index.html to NGINX root
    - name: Deploy custom index.html to NGINX root
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>My Portfolio</title>
            <style>
              @keyframes colorChange {
                0% { color: red; }
                50% { color: green; }
                100% { color: blue; }
              }
              h1 {
                animation: colorChange 2s infinite;
              }
            </style>
          </head>
          <body>
            <h1>Hello this is Pranay Sawant</h1>
            <h2>YT: <span style="color:green">devopsSolutions</span></h2>
            <p>pls like and suscribe</p>
          </body>
          </html>
      tags: [nginx, content]

    # ----------------------------------------
    # Optional: Copy full website folder
    # Uncomment this block if using /website dir
    # ----------------------------------------
    #
    # - name: Copy website folder to NGINX root
    #   copy:
    #     src: ../website/
    #     dest: /var/www/html/
    #     owner: www-data
    #     group: www-data
    #     mode: '0644'
    #   notify: restart nginx
    #   tags: [nginx, content]

    # Task 5: Configure UFW firewall
    - name: Allow HTTP traffic through firewall
      ufw:
        rule: allow
        port: "{{ nginx_port }}"
        proto: tcp
      tags: [security]

    - name: Allow SSH traffic through firewall
      ufw:
        rule: allow
        port: "22"
        proto: tcp
      tags: [security]

    - name: Enable UFW firewall
      ufw:
        state: enabled
        policy: deny
      tags: [security]

    # Task 6: Verify NGINX is serving content
    - name: Test NGINX is responding
      uri:
        url: "http://localhost:{{ nginx_port }}"
        method: GET
        status_code: 200
      register: nginx_test
      tags: [verification]

    - name: Show deployment result
      debug:
        msg: |
          NGINX Deployment Successful!
          Access your site at: http://{{ ansible_default_ipv4.address }}
          NGINX Status: {{ nginx_test.status }}
      when: nginx_test.status == 200
      tags: [verification]

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
      tags: [nginx]
