# ansible/playbooks/deploy-nginx.yml
---
- name: Deploy NGINX to EC2 Instance
  hosts: ec2_servers          # Target servers from inventory
  become: yes                 # Use sudo privileges
  gather_facts: yes          # Collect system information
  
  vars:
    nginx_port: 80           # Port NGINX will listen on
    
  tasks:
    # Task 1: Update system packages
    # Why: Ensures we have latest security patches
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache valid for 1 hour
      tags: [system]
      
    # Task 2: Install NGINX
    # Why: This is our main web server
    - name: Install NGINX
      apt:
        name: nginx
        state: present          # Ensure it's installed
      notify: restart nginx     # Trigger restart if installed
      tags: [nginx]
      
    # Task 3: Start and enable NGINX service
    # Why: Ensures NGINX starts now and after reboots
    - name: Start and enable NGINX
      systemd:
        name: nginx
        state: started          # Start the service
        enabled: yes           # Enable auto-start on boot
      tags: [nginx]
      
    # Task 4: Configure UFW firewall
    # Why: Security - only allow necessary ports
    - name: Allow HTTP traffic through firewall
      ufw:
        rule: allow
        port: "{{ nginx_port }}"
        proto: tcp
      tags: [security]
      
    - name: Allow SSH traffic through firewall
      ufw:
        rule: allow
        port: "22"
        proto: tcp
      tags: [security]
      
    - name: Enable UFW firewall
      ufw:
        state: enabled
        policy: deny           # Deny all by default
      tags: [security]
      
    # Task 5: Verify NGINX is serving content
    # Why: Confirms our deployment worked
    - name: Test NGINX is responding
      uri:
        url: "http://localhost:{{ nginx_port }}"
        method: GET
        status_code: 200       # Expect successful response
      register: nginx_test
      tags: [verification]
      
    # Task 6: Display deployment status
    - name: Show deployment result
      debug:
        msg: |
          NGINX Deployment Successful!
          Access your site at: http://{{ ansible_default_ipv4.address }}
          NGINX Status: {{ nginx_test.status }}
      when: nginx_test.status == 200
      tags: [verification]
  
  # Handlers: Tasks that run when notified
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
      tags: [nginx]
